//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.SampleAlarms
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class SampleAlarms { }
#else

	public class SampleAlarms : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public SampleAlarms()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/MetroAlarm;component/SampleData/SampleAlarms/SampleAlarms.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private ItemCollection _Collection = new ItemCollection();

		public ItemCollection Collection
		{
			get
			{
				return this._Collection;
			}
		}
	}

	public class ItemCollection : System.Collections.ObjectModel.ObservableCollection<Item>
	{ 
	}

	public class Item : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private bool _Name = false;

		public bool Name
		{
			get
			{
				return this._Name;
			}

			set
			{
				if (this._Name != value)
				{
					this._Name = value;
					this.OnPropertyChanged("Name");
				}
			}
		}

		private string _Desc = string.Empty;

		public string Desc
		{
			get
			{
				return this._Desc;
			}

			set
			{
				if (this._Desc != value)
				{
					this._Desc = value;
					this.OnPropertyChanged("Desc");
				}
			}
		}

		private string _alarmTime = string.Empty;

		public string alarmTime
		{
			get
			{
				return this._alarmTime;
			}

			set
			{
				if (this._alarmTime != value)
				{
					this._alarmTime = value;
					this.OnPropertyChanged("alarmTime");
				}
			}
		}

		private string _enabled = string.Empty;

		public string enabled
		{
			get
			{
				return this._enabled;
			}

			set
			{
				if (this._enabled != value)
				{
					this._enabled = value;
					this.OnPropertyChanged("enabled");
				}
			}
		}
	}
#endif
}
